name: UltraBar
version: 2.3.0
main: me.ryandw11.ultrabar.UltraBar
author: Ryandw11
description: Use Titles, Actionbars, and Boss bars!
softdepend: [WorldGuard, WorldEdit, PlaceholderAPI]
api-version: 1.13
commands:
    bar:
     description: use boss bars!
     aliases: [ubar, bossbar]
    utitle:
     description: use titles!
     aliases: [ut, ultratitle]
    actionbar:
     description: use actionbars!
     aliases: [ab, uactionbar, uab]
    UltraBar:
     description: Help Command
     aliases: [ub, ultrab]